config/routes.rb
Rails.application.routes.draw do
  resources :wishes
  resources :loans
  resources :publications
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"
  get "admin/home" => "home#admin", :as => "admin/home"
  get "manager/home" => "home#manager", :as => "manager/home" 
  get "reader/home" => "home#reader", :as => "reader/home"
  get "loans/:id/return" => "loans#bookreturn", :as => "loans/return"
  post "loans/:id/return" => "loans#bookreturning"
  resources :users
  resources :session
  root :to => "home#index"

end

app/models/publication.rb
class Publication < ActiveRecord::Base
	self.inheritance_column = "not_sti"
	has_many :loans
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:isbn, :title, :author, :year, :type, :available)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.select(:type, options_for_select([['Physical','physical'],['Electronic','electronic']], 'physical')) %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.select(:available, options_for_select([['Yes','yes'],['No','no']], 'yes')) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing Publication</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Publications</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Author</th>
      <th>Year</th>
      <th>Type</th>
      <th>Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.isbn %></td>
        <td><%= publication.title %></td>
        <td><%= publication.author %></td>
        <td><%= publication.year %></td>
        <td><%= publication.type %></td>
        <td><%= publication.available %></td>
        <td><%= link_to 'Show', publication %></td>
        <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
        <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New Publication</h1>

<%= render 'form' %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isbn:</strong>
  <%= @publication.isbn %>
</p>

<p>
  <strong>Title:</strong>
  <%= @publication.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @publication.author %>
</p>

<p>
  <strong>Year:</strong>
  <%= @publication.year %>
</p>

<p>
  <strong>Type:</strong>
  <%= @publication.type %>
</p>

<p>
  <strong>Available:</strong>
  <%= @publication.available %>
</p>

<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>