config/routes.rb
Rails.application.routes.draw do
  resources :wishes
  resources :loans
  resources :publications
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"
  get "admin/home" => "home#admin", :as => "admin/home"
  get "manager/home" => "home#manager", :as => "manager/home" 
  get "reader/home" => "home#reader", :as => "reader/home"
  get "loans/:id/return" => "loans#bookreturn", :as => "loans/return"
  post "loans/:id/return" => "loans#bookreturning"
  resources :users
  resources :session
  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@_current_user = session[:user]
		@_current_role = session[:role]
		if !@_current_user
				
		else
			if @_current_role == "admin"
				#redirect_to "admin/home", :notice => "Logged in admin!"
				redirect_to :controller => 'home' , :action => 'admin' ,:notice => "Logged in admin!"
			elsif @_current_role == "manager"
				redirect_to :controller => 'home' , :action => 'manager' ,:notice => "Logged in manager!"
			elsif @_current_role == "reader"
				redirect_to :controller => 'home' , :action => 'reader' ,:notice => "Logged in reader!"
			end 
		end
	end

	def admin
	end

	def manager
	end

	def reader
	end

end

app/views/home/admin.html.erb
<p id="notice"><%= notice %></p>

  <div class="jumbotron">
    <h1>Welcome <%= session[:user] %> </h1>      
    <p>In your admin menu you can manage loans, users and publications. Enjoy the app!</p>
  </div>
  
<!-- <%= link_to(image_tag("icons/T-Shirt.png", :alt => "home image", :width => 100, :height => 100, :title => "Users"), users_path) %>
<%= link_to(image_tag("icons/Document.png", :alt => "home image", :width => 100, :height => 100, :title => "Publications"), publications_path) %>
<%= link_to(image_tag("icons/Shopping.png", :alt => "home image", :width => 100, :height => 100, :title => "Loans"), loans_path) %>

<%= link_to "Users", users_path %>
<%= link_to "Publications", publications_path %>
<%= link_to "Loans", loans_path %> -->
 
 <div class="row">
  <div class="col-md-2">
    <div class="thumbnail">
      <%= link_to(image_tag("icons/T-Shirt.png", :alt => "home image", :width => 100, :height => 100, :title => "Users"), users_path) %>
      <div class="caption" style="text-align: center">
        <h4><%= link_to "Users", users_path %></h4>
        <!--<p>Create, update, read and delete users.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>
 
  <div class="col-md-2">
    <div class="thumbnail">
      <%= link_to(image_tag("icons/Document.png", :alt => "home image", :width => 100, :height => 100, :title => "Publications"), publications_path) %>
      <div class="caption" style="text-align: center">
        <h4><%= link_to "Publications", publications_path %></h4>
        <!--<p>Create, update, read and delete users.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>

  <div class="col-md-2">
    <div class="thumbnail">
      <%= link_to(image_tag("icons/Shopping.png", :alt => "home image", :width => 100, :height => 100, :title => "Loans"), loans_path) %>
      <div class="caption" style="text-align: center">
        <h4><%= link_to "Loans", loans_path %></h4>
        <!--<p>Create, update, read and delete users.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
</div>

 
<!-- <%= link_to 'New User', new_user_path %> -->

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to our App!</h1>
<br>
<div class="row">
  <div class="col-md-6">
      <%= link_to(image_tag("welcome.jpg", :alt => "home image", :width => 575, :height => 455, :title => "Users"), users_path) %>
  </div>
  <div class="col-md-6">
      
      <div class="row">
          <div class="col-md-1">
              <br><br><br><br><br><br><br><br><br><br>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4"><a href="signup" class="btn btn-lg btn-success" style="text-align: center"><span class="glyphicon glyphicon-log-in"></span> Sign up now!</a> </div>
          <div class="col-md-4"></div>
        </div>
      
      </div>
</div>

app/views/home/manager.html.erb
<p id="notice"><%= notice %></p>

  <div class="jumbotron">
    <h1>Welcome <%= session[:user] %> </h1>      
    <p>In your manager menu you can manage loans, readers and publications. Enjoy the app!</p>
  </div>

<!-- <%= link_to(image_tag("icons/T-Shirt.png", :alt => "home image", :width => 100, :height => 100, :title => "Readers"), users_path) %>

<%= link_to(image_tag("icons/Document.png", :alt => "home image", :width => 100, :height => 100, :title => "Publications"), publications_path) %>

<%= link_to(image_tag("icons/Shopping.png", :alt => "home image", :width => 100, :height => 100, :title => "Loans"), loans_path) %> -->

 <div class="row">
  <div class="col-md-2">
    <div class="thumbnail">
      <%= link_to(image_tag("icons/T-Shirt.png", :alt => "home image", :width => 100, :height => 100, :title => "Readers"), users_path) %>
      <div class="caption" style="text-align: center">
        <h4><%= link_to "Users", users_path %></h4>
        <!--<p>Create, update, read and delete users.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>
 
  <div class="col-md-2">
    <div class="thumbnail">
      <%= link_to(image_tag("icons/Document.png", :alt => "home image", :width => 100, :height => 100, :title => "Publications"), publications_path) %>
      <div class="caption" style="text-align: center">
        <h4><%= link_to "Publications", publications_path %></h4>
        <!--<p>Create, update, read and delete users.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>

  <div class="col-md-2">
    <div class="thumbnail">
     <%= link_to(image_tag("icons/Shopping.png", :alt => "home image", :width => 100, :height => 100, :title => "Loans"), loans_path) %>
      <div class="caption" style="text-align: center">
        <h4><%= link_to "Loans", loans_path %></h4>
        <!--<p>Create, update, read and delete users.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
</div>

app/views/home/reader.html.erb
<p id="notice"><%= notice %></p>

  <div class="jumbotron">
    <h1>Welcome <%= session[:user] %> </h1>      
    <p>In your reader menu you can view your loans and make your wish list. Enjoy the app!</p>
  </div>

<!-- <%= link_to(image_tag("icons/Shopping.png", :alt => "home image", :width => 100, :height => 100, :title => "Loans"), loans_path) %>

<%= link_to(image_tag("icons/Bookmark.png", :alt => "home image", :width => 100, :height => 100, :title => "My Wishes"), wishes_path) %> -->


 <div class="row">
  <div class="col-md-2">
    <div class="thumbnail">
      <%= link_to(image_tag("icons/Shopping.png", :alt => "home image", :width => 100, :height => 100, :title => "Loans"), loans_path) %>
      <div class="caption" style="text-align: center">
        <h4><%= link_to "Loans", loans_path %></h4>
        <!--<p>Create, update, read and delete users.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
  </div>

  <div class="col-md-2">
    <div class="thumbnail">
     <%= link_to(image_tag("icons/Bookmark.png", :alt => "home image", :width => 100, :height => 100, :title => "My Wishes"), wishes_path) %>
      <div class="caption" style="text-align: center">
        <h4><%= link_to "My Wishes", wishes_path %></h4>
        <!--<p>Create, update, read and delete users.</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p> -->
      </div>
    </div>
</div>