config/routes.rb
Rails.application.routes.draw do
  resources :wishes
  resources :loans
  resources :publications
  get "logout" => "session#destroy", :as => "logout"
  get "login" => "session#new", :as => "login"
  post "login" => "session#create"
  get "signup" => "users#new", :as => "signup"
  get "admin/home" => "home#admin", :as => "admin/home"
  get "manager/home" => "home#manager", :as => "manager/home" 
  get "reader/home" => "home#reader", :as => "reader/home"
  get "loans/:id/return" => "loans#bookreturn", :as => "loans/return"
  post "loans/:id/return" => "loans#bookreturning"
  resources :users
  resources :session
  root :to => "home#index"

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :user
  belongs_to :publication
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy, :bookreturning, :bookreturn]

  # GET /loans
  # GET /loans.json
  def index
    if (session[:role] == 'admin') or (session[:role] == 'manager')
      @loans = Loan.all
    elsif session[:role] == 'reader'
      @user = User.find_by name: session[:user]
      @loans = Loan.where(user_id: @user.id)
    end
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      @publication = Publication.find_by id: @loan.publication_id
      if @publication.available=='yes'
        if @publication.type=='physical'
          @publication.available='no'
          @publication.save
        end
        if @loan.save
          format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
          format.json { render :show, status: :created, location: @loan }
        else
          format.html { render :new }
          format.json { render json: @loan.errors, status: :unprocessable_entity }
        end
        
      else
        format.html { redirect_to loans_path, notice: 'This publication is not available.' }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @publication = Publication.find_by id: @loan.publication_id
    if @publication.available=='no'
      @publication.available='yes'
      @publication.save
    end
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def bookreturn
  end
  
  def bookreturning
    respond_to do |format|
      @publication = Publication.find_by id: @loan.publication_id
      if @publication.available=='no'
        @publication.available='yes'
        @publication.save
      end
      
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully returned.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :bookreturn }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:user_id, :publication_id, :start_date, :end_date)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select(:user_id, User.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :publication_id %><br>
    <%= f.collection_select(:publication_id, Publication.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date, {:order => [:day, :month, :year]} %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date, :default => {:day => 15.days.from_now.day}, :order => [:day, :month, :year] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loans/bookreturn.html.erb
<h1>Book Return</h1>

<!-- <%= render 'form' %> -->

<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= @loan.user.name %>
    <!-- <%= f.collection_select(:user_id, User.all, :id, :name) %> -->
  </div>
  <div class="field">
    <%= f.label :publication_id %><br>
    <%= @loan.publication.title %>
    <!-- <%= f.collection_select(:publication_id, Publication.all, :id, :title) %> -->
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date ,{disabled: true, :order => [:day, :month, :year]} %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date ,{disabled: false, :order => [:day, :month, :year]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Loans</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User</th>
      <th>Publication</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.user.name %></td>
        <td><%= loan.publication.title %></td>
        <td><%= loan.start_date.to_formatted_s(:rfc822) %></td>
        <td><%= loan.end_date.to_formatted_s(:rfc822) %></td>
        <td><%= link_to 'Show', loan %></td>

        <% if session[:role] == 'admin' or session[:role] == 'manager' %>
            <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
            <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'Return Book', loans_return_path(loan) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if session[:role] == 'admin' or session[:role] == 'manager' %>
<%= link_to 'New Loan', new_loan_path %>
<% end %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @loan.user.name %>
</p>

<p>
  <strong>Publication:</strong>
</p>
<p>
  Isbn: 
  <%= @loan.publication.isbn %>
</p>
<p>
  Title:
  <%= @loan.publication.title %>
</p>
<p>
  <strong>Start date:</strong>
  <%= @loan.start_date.to_formatted_s(:rfc822) %>
</p>

<p>
  <strong>End date:</strong>
  <%= @loan.end_date.to_formatted_s(:rfc822) %>
</p>

<%= link_to 'Edit', edit_loan_path(@loan) %> |
<%= link_to 'Back', loans_path %>